server:
  port: 9090
spring:
  application:
    name: movie-booking-service
  datasource:
    url: jdbc:mysql://localhost:3306/movieticketbookings?createDatabaseIfNotExist=true
    username: root
    password: Ravikiran@123
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: update